### ISSUE TITLE
Use tag lists in the front matter instead of an array

### ISSUE THREAD

**Issue by argenos** [akosbalasko/zoottelkeeper-obsidian-plugin#27]
Instead of the default:

```yaml
---
alias:
- 
tags: [MOC]
---
```

I'd like to be able to format my tags using lists: 

```yaml
---
alias:
- 
tags:
- MOC
---
```
